import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname } from 'node:path';
import { Document, parse as parseYaml, stringify as stringifyYaml } from 'yaml';
import { HuskError, parseSpec } from '@husk-ai/core';
import type { HuskSpec } from '@husk-ai/core';

/**
 * husk.yaml on disk.
 *
 * The file is meant to be opened, read and edited by a person, so the key order
 * is deliberate -- who the bot is, then what it knows, then what it may do --
 * and multi-line strings are literal blocks instead of one long quoted line.
 * No anchors: a `&persona` reference saves bytes and costs a reader a minute.
 */

/** Identity first, then behaviour, then capability, then policy. */
const KEY_ORDER: Array<keyof HuskSpec> = [
  'apiVersion',
  'name',
  'displayName',
  'version',
  'description',
  'model',
  'fallbackModels',
  'temperature',
  'persona',
  'knowledge',
  'examples',
  'tools',
  'computer',
  'limits',
  'guardrails',
  'memory',
  'triggers',
  'metadata',
  'origin',
];

export interface SerializeOptions {
  /** Header comment. Pass null for no header. */
  header?: string | null;
  /** Name the transcript this husk came from, in the header. */
  sourceLabel?: string;
}

function ordered(spec: HuskSpec): Record<string, unknown> {
  const src = spec as unknown as Record<string, unknown>;
  const out: Record<string, unknown> = {};
  for (const key of KEY_ORDER) {
    const v = src[key as string];
    if (v !== undefined) out[key as string] = v;
  }
  // Anything the schema grows later still gets written.
  for (const [k, v] of Object.entries(src)) if (!(k in out) && v !== undefined) out[k] = v;
  return out;
}

function defaultHeader(spec: HuskSpec, sourceLabel?: string): string {
  const lines = [
    ` ${spec.displayName ?? spec.name} -- a husk.`,
    ` Generated by @husk-ai/sessions. Edit freely; this file is the whole bot.`,
  ];
  const label = sourceLabel ?? spec.origin?.source;
  if (label) lines.push(` Distilled from: ${label}`);
  if (spec.origin?.messageCount !== undefined) lines.push(` Messages read: ${spec.origin.messageCount}`);
  if (spec.origin?.importedAt) lines.push(` Imported: ${spec.origin.importedAt}`);
  return lines.join('\n');
}

const YAML_OPTIONS = {
  // Never fold: a folded persona is a persona nobody can diff.
  lineWidth: 0,
  // Force literal blocks for anything containing a newline.
  blockQuote: 'literal' as const,
  // No `&anchor` / `*alias`.
  aliasDuplicateObjects: false,
  indent: 2,
  nullStr: '',
};

export function stringifySpec(spec: HuskSpec, opts: SerializeOptions = {}): string {
  const doc = new Document(ordered(spec));
  if (opts.header !== null) doc.commentBefore = opts.header ?? defaultHeader(spec, opts.sourceLabel);
  return doc.toString(YAML_OPTIONS);
}

/** Parse a husk.yaml string. Throws a HuskError with the YAML position on failure. */
export function parseSpecYaml(text: string, origin = 'husk.yaml'): HuskSpec {
  let data: unknown;
  try {
    data = parseYaml(text);
  } catch (cause) {
    const message = cause instanceof Error ? cause.message : String(cause);
    throw new HuskError('E_SPEC_INVALID', `${origin} is not valid YAML: ${message}`, {
      hint: 'Check indentation, and that any string with a colon in it is quoted.',
      cause,
    });
  }
  if (data === null || data === undefined) {
    throw new HuskError('E_SPEC_INVALID', `${origin} is empty.`, {
      hint: 'Run `husk init` to write a starting husk.yaml.',
    });
  }
  return parseSpec(data);
}

export async function readSpec(filePath: string): Promise<HuskSpec> {
  let text: string;
  try {
    text = await readFile(filePath, 'utf8');
  } catch (cause) {
    throw new HuskError('E_SPEC_INVALID', `Cannot read ${filePath}.`, {
      hint: 'Check the path, or run `husk init` to create one.',
      cause,
    });
  }
  return parseSpecYaml(text, filePath);
}

export async function writeSpec(
  filePath: string,
  spec: HuskSpec,
  opts: SerializeOptions = {},
): Promise<string> {
  const text = stringifySpec(spec, opts);
  await mkdir(dirname(filePath), { recursive: true });
  await writeFile(filePath, text, 'utf8');
  return text;
}

/** Escape hatch for callers that want raw YAML with the same house style. */
export function toYaml(value: unknown): string {
  return stringifyYaml(value, YAML_OPTIONS);
}
