#!/usr/bin/env node
/**
 * Regenerate `src/driver.ts` from `src/driver.py`.
 *
 * The driver has to reach the computer as a string, and the build contract is
 * `tsc` alone -- no asset copying, no bundler step. So the Python is embedded.
 * It is still a real `.py` file, because a two-hundred-line program wedged in a
 * template literal is a program nobody will ever edit, lint, or run by hand.
 *
 * `driver.test.ts` fails if the two ever drift, so forgetting to run this is a
 * red test rather than a browser that misbehaves in production.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const src = join(here, '..', 'src');

const python = readFileSync(join(src, 'driver.py'), 'utf8').replace(/\r\n/g, '\n');

const out = `// GENERATED by scripts/embed-driver.mjs from src/driver.py -- do not edit by hand.
import { CACHE_ROOT } from './provision.js';

/** Where the driver lands inside the computer. Under the browser cache so \`persist\` keeps it. */
export const DRIVER_PATH = \`\${CACHE_ROOT}/driver.py\`;

/**
 * \`src/driver.py\`, verbatim.
 *
 * Embedded rather than shipped as an asset because the build is \`tsc\` and
 * nothing else, and a \`dist\` that silently lacks its driver is a failure mode
 * worth designing out.
 */
export const DRIVER_SOURCE = ${JSON.stringify(python)};
`;

writeFileSync(join(src, 'driver.ts'), out);
process.stdout.write(`embedded ${python.length} bytes of driver.py into src/driver.ts\n`);
